config/routes.rb
Rails.application.routes.draw do

  #管理者新規登録・パスワード機能は不要とするため、不要となるルーティングをスキップする↓
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
  end

  scope module: :public do
    devise_for :users, controllers: { 
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations' 
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  
    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'users/mypage' => 'users#mypage', as: 'mypage'
    resources :users, only: [:show, :index]
    resources :plans do
      resources :comments, only: [:create, :destroy]
    end
    resources :spots do
      resources :spot_images, only: [:destroy]

    end
    get "search" => "searches#search"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true 
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plans, inverse_of: :user,dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :profile_image
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.looks(search, word) #self.looks クラス全体にlooksメソッド使うためにself.使ってる。
    if search == "perfect_match" #完全一致の場合
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match" #前方一致
      User.where("name LIKE?","#{word}%")
    elsif search == "backward_match" #後方一致
      User.where("name LIKE?","%#{word}")
    elsif search == "partial_match" #部分一致
      User.where("name LIKE?","%#{word}%")
    else
      User.all #上の検索条件に当てはまらなかったら、全ユーザ取得する
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin' #admin.html.erbを適用するため
  before_action :authenticate_admin!
  
  def show
    @user = User.find(params[:id])
    @plans = @user.plans
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notie: 'ユーザーを削除しました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container mt-5">
  <h3><i class="fa-solid fa-face-smile"></i><%= @user == current_user ? "My page" : "#{@user.name}さんのページ" %></h3>

  <div>
    <h4><%= @user.name %></h4>
    <%= image_tag @user.get_profile_image(200,200) %>

    <% if @user == current_user && !@user.guest_user? %>
      <p><%= link_to "編集", edit_user_registration_path, class: 'btn btn-outline-info my-3' %></p>
    <% end %>
  </div>

  <% if @user == current_user %>
    <%= link_to "新規プラン投稿する", new_plan_path, class: 'btn btn-outline-info mb-3' %>
  <% end %>
 
  <h4><i class="fa-solid fa-person-walking-luggage"></i>プラン一覧</h4> 

  <div class="row">
    <% @plans.each do |plan| %>
      <div class="col-md-4 mb-3">
        <div class="text-center p-3 border rounded">
          <%= link_to plan.title, plan_path(plan), class: 'text-dark text-decoration-none' %>
            <div class="text-muted small"><i class="fa-regular fa-comment fa-flip-horizontal"></i>：<%= plan.comments.count %></div>
        </div>
      </div>
    <% end %>
  </div>

  
  <div class="mt-5">
    <%= link_to 'ユーザー一覧', users_path, class: 'btn btn-outline-secondary btn-sm' %>  <%= link_to 'プラン一覧', plans_path, class: 'btn btn-outline-secondary btn-sm' %>
  </div>
</div>