config/routes.rb
Rails.application.routes.draw do

  #管理者新規登録・パスワード機能は不要とするため、不要となるルーティングをスキップする↓
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
  end

  scope module: :public do
    devise_for :users, controllers: { 
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations' 
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  
    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'users/mypage' => 'users#mypage', as: 'mypage'
    resources :users, only: [:show, :index]
    resources :plans do
      resources :comments, only: [:create, :destroy]
    end
    resources :spots do
      resources :spot_images, only: [:destroy]

    end
    get "search" => "searches#search"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email] 
  #admin側でemail使ってログインするために必要
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  validates :text, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :spots, inverse_of: :plan, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :spots, allow_destroy: true, reject_if: :all_blank
  validates_associated :spots

  validates :title, presence: true, length: { maximum: 100 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_end_check

  def start_end_check
    errors.add(:end_date, "は旅行開始日より前の日付では登録できません。") unless
    self.start_date <= self.end_date 
  end

  def self.looks(search, word) #self.looks クラス全体にlooksメソッド使うためにself.使ってる。
    if search == "perfect_match" #完全一致の場合
      Plan.where("title LIKE?", "#{word}")
    elsif search == "forward_match" #前方一致
      Plan.where("title LIKE?","#{word}%")
    elsif search == "backward_match" #後方一致
      Plan.where("title LIKE?","%#{word}")
    elsif search == "partial_match" #部分一致
      Plan.where("title LIKE?","%#{word}%")
    else
      Plan.all #上の検索条件に当てはまらなかったら、全ユーザ取得する
    end
  end
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :spot

  enum transportation: {
    walk: 0, train: 1, bus: 2, car: 3, ship: 4, bicycle: 5, airplane: 6
  }

  validates :departure, presence: true
  validates :arrival, presence: true
  validates :visit_order,  presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :travel_time,  presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :plan 
  has_many :routes, inverse_of: :spot, dependent: :destroy
  accepts_nested_attributes_for :routes, allow_destroy: true, reject_if: :all_blank
  has_many_attached :images

  validates :name, presence: true, length: { maximum: 100 }
  validates :staying_start, presence: true
  validates :staying_end, presence: true
  validates :visit_order, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode

  validate :start_end_check

  def start_end_check
    errors.add(:staying_end, "は滞在開始時間より前の時間では登録できません。") unless
    self.staying_start <= self.staying_end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true 
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plans, inverse_of: :user,dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :profile_image
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.looks(search, word) #self.looks クラス全体にlooksメソッド使うためにself.使ってる。
    if search == "perfect_match" #完全一致の場合
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match" #前方一致
      User.where("name LIKE?","#{word}%")
    elsif search == "backward_match" #後方一致
      User.where("name LIKE?","%#{word}")
    elsif search == "partial_match" #部分一致
      User.where("name LIKE?","%#{word}%")
    else
      User.all #上の検索条件に当てはまらなかったら、全ユーザ取得する
    end
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true
class Admin::SessionsController < Devise::SessionsController
  layout 'admin' #admin.html.erbを適用するため
 
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def after_sign_in_path_for(resource) #ログイン後のリダイレクト先 
    admin_dashboards_path
  end

  def after_sign_out_path_for(resource) #ログアウト後のリダイレクト先
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin' #admin.html.erbを適用するため
  before_action :authenticate_admin!
  
  def show
    @user = User.find(params[:id])
    @plans = @user.plans
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notie: 'ユーザーを削除しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #ログイン認証が成功していないと、トップ/アバウトページ以外の画面(ログイン/サインアップ除く)表示されないように
  #エンドユーザー側のauthenticate_user!フィルターが適用されないように。かわりに管理者用コントローラで認証（authenticate_admin!)する
  before_action :authenticate_user!, except: [:top, :about], unless: :admin_controller? 
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image])
  end

  def after_sign_in_path_for(resource)
    mypage_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_update_path_for(resource)
    mypage_path
  end
  
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/spot_images_helper.rb
module SpotImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="container">
  <div class="text-center">
    <h2 class="m-3">What about Travelers!!</h2>
    <p class="mb-5">Travelersは「旅の思い出を残したい人」や<br>
      「旅行は好きだけどプランを立てるのはちょっと苦手...」<br>
       という人のための旅行プラン共有サイトです！！
    </p>

    <div class="row">
      <div class="col-md-6">
        <h4>「自分で考えたプランで旅行に行く人」！！</h4>
        <p>たくさん調べたのに旅行後しばらく経つと忘れてしまって、<br>
           どうやって行ったけ？ってなることありませんか？</p>
        <p>またこのプランで行きたいな〜と思っても忘れちゃうと勿体ナイ！！</p>
        <p>旅の思い出を残して、いつでも振り返れるようにしよう！</p>
        <p>旅行プランを投稿して、次の旅にも活かせる記録を作ろう！！</p>

        <%= link_to users_guest_sign_in_path, method: :post, class:'btn btn-outline-info mb-3' do %>
          <i class="fa-solid fa-face-grin-squint"></i> Guest Log in（閲覧用）
        <% end %>
        <%= link_to new_user_session_path, class:'btn btn-info mb-3' do %>
          <i class="fa-solid fa-right-to-bracket"></i>  Log in
        <% end %>
        <%= link_to new_user_registration_path, class:'btn btn-info mb-3' do %>
          <i class="fa-solid fa-user-plus"></i> Sign up
        <% end %>
      </div>
      <div class="col-md-6">
        <h4>「旅行は好きだけどプランを立てるのはちょっと苦手...」な方！！</h4>
        <p>どこに行こう？どうやって行こう？<br>
           目的地は決まったけど他どうしよう、、？
        </p>
        <p>迷いすぎてせっかくの旅行なのにプランニングで疲れちゃう！って時！</p>
        <p>誰かの旅行プランを参考にして、素敵なスポットに出会おう！</p>
        <p>プランに迷ったとき、きっと役に立つアイデアがあるかもしれない！ </p>

        <%= link_to users_guest_sign_in_path, method: :post, class:'btn btn-outline-info mb-3' do %>
          <i class="fa-solid fa-face-grin-squint"></i> Guest Log in（閲覧用）
        <% end %>
        <%= link_to new_user_session_path, class:'btn btn-info mb-3' do %>
          <i class="fa-solid fa-right-to-bracket"></i>  Log in
        <% end %>
        <%= link_to new_user_registration_path, class:'btn btn-info mb-3' do %>
          <i class="fa-solid fa-user-plus"></i> Sign up
        <% end %>
      </div>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-5">
  <div class="text-center">
    <h1 class="mb-3">Welcome to Travelers!!</h1>
    <h2 class="mb-4">Your Trip, Someone's Inspiration!!</h2>
    <p class="mb-5">
      あなたの旅の記録が誰かの旅のきっかけになる！<br>
      旅の記録を残そう！誰かの旅を覗き見しよう！！
    </p>
    <div class="d-grid gap-3 col-6 mx-auto">

      <%= link_to about_path, class:'btn btn-outline-info mb-3' do %>
        <i class="fa-solid fa-link"></i> About
      <% end %>

      <%= link_to users_guest_sign_in_path, method: :post, class:'btn btn-outline-info mb-3' do %>
        <i class="fa-solid fa-face-grin-squint"></i> Guest Log in（閲覧用）
      <% end %>

      
      <div class="d-grid gap-3 col-6 mx-auto">
        <%= link_to new_user_session_path, class:'btn btn-info mb-3' do %>
           <i class="fa-solid fa-right-to-bracket"></i>  Log in
        <% end %>

        <%= link_to new_user_registration_path, class:'btn btn-info mb-3' do %>
          <i class="fa-solid fa-user-plus"></i> Sign up
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div>
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Plan']]) %>
      <!-- UserかPlanを選択するセレクトボックス --!>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <!-- 検索方法セレクト --!>
      <%= f.submit "検索", class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>
  </div>
<% end %>

app/views/searches/search_result.html.erb
<div class="container mt-5">
  <h2 class="mb-4">
  <i class="fa-solid fa-magnifying-glass"></i> 検索結果
  </h2>

  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <% if @users.present? %>
      <div class="row">
        <% @users.each do |user| %>
          <div class="col-md-4 mb-3">
            <div class="text-center p-3 border rounded">
              <%= link_to user.name, user_path(user), class: 'text-dark text-decoration-none' %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>該当するユーザーは見つかりませんでした。</p>
    <% end %>

  <% elsif @range == "Plan" %>
    <% if @plans.present? %>
      <div class="row">
        <% @plans.each do |plan| %>
          <div class="col-md-4 mb-3">
            <div class="text-center p-3 border rounded">
              <%= link_to plan.title, plan_path(plan), class: 'text-dark text-decoration-none' %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>該当する旅行プランは見つかりませんでした。</p>
    <% end %>
  <% end %>

  </div>