config/routes.rb
Rails.application.routes.draw do

  #管理者新規登録・パスワード機能は不要とするため、不要となるルーティングをスキップする↓
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
  end

  scope module: :public do
    devise_for :users, controllers: { 
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations' 
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  
    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'users/mypage' => 'users#mypage', as: 'mypage'
    resources :users, only: [:show, :index]
    resources :plans do
      resources :comments, only: [:create, :destroy]
    end
    resources :spots do
      resources :spot_images, only: [:destroy]

    end
    get "search" => "searches#search"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :spots, inverse_of: :plan, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :spots, allow_destroy: true, reject_if: :all_blank
  validates_associated :spots

  validates :title, presence: true, length: { maximum: 100 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_end_check

  def start_end_check
    errors.add(:end_date, "は旅行開始日より前の日付では登録できません。") unless
    self.start_date <= self.end_date 
  end

  def self.looks(search, word) #self.looks クラス全体にlooksメソッド使うためにself.使ってる。
    if search == "perfect_match" #完全一致の場合
      Plan.where("title LIKE?", "#{word}")
    elsif search == "forward_match" #前方一致
      Plan.where("title LIKE?","#{word}%")
    elsif search == "backward_match" #後方一致
      Plan.where("title LIKE?","%#{word}")
    elsif search == "partial_match" #部分一致
      Plan.where("title LIKE?","%#{word}%")
    else
      Plan.all #上の検索条件に当てはまらなかったら、全ユーザ取得する
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true, html: { multipart: true } ) do |f| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= plan.errors.count %> 件のエラーが発生しています。</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :start_date, "旅行日" %><br>
      <%= f.date_select :start_date %>
        <span>~</span>
      <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :body, "プランについて" %><br>
    <%= f.text_area :body %>
  </div>

  <div id="spot">
    <%= f.fields_for :spots do |spot| %>
      <%= render 'spot_fields', f: spot %>
    <% end %>
  </div>
  <div class="links">
    <%= link_to_add_association 'スポット追加', f, :spots , class: 'btn btn-outline-info btn-sm mb-3' %>
  </div>

  <div class="actions">
    <%= f.submit '投稿する', class:'btn btn-info btn-lg mb-3' %>
  </div>
<% end %>

app/views/plans/_route_fields.html.erb
<div class="nested-fields">

  <div class="field">
    <%= f.label :departure, '出発地' %><br>
    <%= f.text_field :departure %>
  </div>

  <div class="field">
    <%= f.label :arrival, '到着地' %><br>
    <%= f.text_field :arrival %>
  </div>

  <div class="field">
  <%= f.label :transportation, '移動方法' %><br>
  <%= f.select :transportation, Route.transportations.keys.map { |k| [t("enums.route.transportation.#{k}"), k] } %>
  </div>  

  <div class="field">
    <%= f.label :travel_time, '移動時間' %><br>
    <%= f.number_field :travel_time, min: 0 %>分
  </div>

  <div class="field">
  <%= f.label :visit_order, '順番' %><br>
  <%= f.number_field :visit_order, min: 1 %>
  </div>

  <div class="field">
  <%= f.label :description, 'ルートについて' %><br>
  <%= f.text_field :description %>
  </div>

  <div class ="links">
   <%= link_to_remove_association "道削除", f, class: 'btn btn-outline-danger btn-sm my-2' %>
  </div>

</div>

app/views/plans/_spot_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name, 'スポット名' %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :images, '写真(複数まとめて選択OK)' %><br>
    <%= f.file_field :images, multiple: true %>

    <% if f.object.images.attached? %>
      <p class="mt-2">投稿済みの写真:</p>
      <% f.object.images.each do |image| %>
        <div class="mb-2">
          <%= image_tag image.variant(resize_to_limit: [150, 150]) %>
          <%= link_to "×削除", spot_spot_image_path(f.object.id, image.id), 
                      method: :delete, 
                      data: { confirm: "この画像を削除しますか？" }, 
                      class: "text-danger ms-2" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :staying_start, '滞在日時' %><br>
    <%= f.datetime_select :staying_start %>
      <span>~</span>
    <%= f.datetime_select :staying_end %>
  </div>

  <div class="field">
    <%= f.label :latitude, '緯度' %><br>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude, '経度' %><br>
    <%= f.text_field :longitude %>
  </div>
  
  <div class="field">
    <%= f.label :visit_order, 'スポット訪問順' %><br>
    <%= f.number_field :visit_order, min: 1 %>
  </div>


  <div class="field">
    <%= f.label :explanation, 'スポットについて' %><br>
    <%= f.text_area :explanation %>
  </div>

  <div id="routes">
    <%= f.fields_for :routes do |route_form| %>
      <%= render 'route_fields', f: route_form %>
    <% end %>
    <div class="links">
      <%= link_to_add_association '道追加', f, :routes, class: 'btn btn-outline-info btn-sm mb-1' %>
    </div>
  </div>

  <div class="actions">
   <%= link_to_remove_association 'スポット削除', f, class: 'btn btn-outline-danger btn-sm mb-2' %>
  </div>
</div>

app/views/plans/edit.html.erb
<div class="container mt-5">
  <h2><i class="fa-solid fa-pencil"></i>旅行プラン編集</h2>

  <%= render 'form', plan: @plan %>

  <%= link_to 'プラン削除',plan_path(@plan), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger mb-3' %>
  <div>
    <%= link_to 'プラン詳細', @plan, class: 'btn btn-outline-secondary btn-sm' %> |
    <%= link_to 'プラン一覧', plans_path, class: 'btn btn-outline-secondary btn-sm' %>
  </div>
</div>

app/views/plans/new.html.erb
<div class="container mt-5">
  <h2><i class="fa-solid fa-pencil"></i>新規プラン投稿</h2>

  <%= render 'form', plan: @plan %>

  <%= link_to 'Back', mypage_path, class: 'btn btn-outline-secondary btn-sm' %>
</div>

app/views/plans/show.html.erb
<div class="container mt-5">
  <p id="notice"><%= notice %></p>

  <h2><i class="fa-solid fa-book-atlas"></i>旅行プラン</h2>

  <p>
    <h4><strong>【<%= @plan.title %>】</strong></h4>
  </p>

  <p>
    投稿者: <%= link_to @plan.user.name, user_path(@plan.user) %>
  </p>

  <!-- レビュー -->

  <p>
    旅行日:
    <%= @plan.start_date %>
    <span>~</span>
    <%= @plan.end_date %>
  </p>

  <% if @plan.body.present? %>
    <i class="fa-regular fa-message fa-flip-horizontal"></i>:<%= @plan.body %>
  <% end %>


  <% @plan.spots.order(:visit_order).each do |spot| %>
    <div class="spot my-4">
      <h4><i class="fa-solid fa-location-dot"></i>: <%= spot.name %></h4>
        <% if spot.images.attached? %>
          <div class="row">
            <% spot.images.each do |image| %>
              <div class="m-3">
                <%= image_tag image.variant(resize_to_limit: [400, 300]) %>
              </div>
            <% end %>
          </div>
        <% end %>
      <p><% if spot.explanation.present? %>
           <i class="fa-regular fa-message fa-flip-horizontal"></i>: <%= spot.explanation %>
         <% end %>
      </p>
      <p><i class="fa-solid fa-clock"></i>: <%= l(spot.staying_start, format: :short) %> ~ <%= l(spot.staying_end, format: :short) %></p>

      <p><i class="fa-solid fa-map-location-dot"></i>(緯度軽度用いて)マップ表示予定</p> 


      <% spot.routes.order(:visit_order).each do |route| %>
        <p>出発地: <%= route.departure %> → 到着地: <%= route.arrival %></p>
        <p>移動方法: <%= t("enums.route.transportation.#{route.transportation}") %></p>
        <p>移動時間: <%= route.travel_time %>分</p> 
          <% if route.description.present? %>
            <i class="fa-regular fa-message fa-flip-horizontal"></i>: <%= route.description %>
          <% end %>
      <% end %>
    </div>
  <% end %>

<div>
  <p><i class="fa-regular fa-comment fa-flip-horizontal"></i> コメント件数：<%= @plan.comments.count %></p>

    <% @plan.comments.each do |comment| %>
      <div class="mb-4 p-3 border rounded">
        <div class="d-flex align-items-start">
          <div class="me-3">
            <%= image_tag comment.user.get_profile_image(50, 50), class: "rounded-circle" %>
          </div>

          <div>
            <div class="fw-bold"><%= comment.user.name %></div>
            <div class="text-muted small"><%= comment.created_at.strftime('%Y/%m/%d') %></div>
           </div>
        </div>

        <div class="mt-2 d-flex justify-content-between align-items-start">
          <p class="mb-1"><%= comment.text %></p>

          <% if comment.user == current_user %>
            <%= link_to "削除", plan_comment_path(comment.plan, comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-sm btn-outline-danger ms-3 " %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>


  <div class="text-end">
    <%= form_with model: [@plan, @comment], local: true do |f| %>
      <%= f.text_area :text, rows: '5', placeholder: "コメントを投稿しよう！", required: true, class: 'form-control mb-2' %>
      <%= f.submit "送信する", class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>
  </div>

  <% if @plan.user == current_user %>
    <%= link_to 'プラン編集', edit_plan_path(@plan), class: 'btn btn-outline-secondary btn-sm mt-5' %> 
  <% end %>
    <%= link_to 'プラン一覧', plans_path, class: 'btn btn-outline-secondary btn-sm mt-5' %>
</div>