config/routes.rb
Rails.application.routes.draw do

  #管理者新規登録・パスワード機能は不要とするため、不要となるルーティングをスキップする↓
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:show, :destroy]
  end

  scope module: :public do
    devise_for :users, controllers: { 
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations' 
    }
    devise_scope :user do
      post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    end
  
    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'users/mypage' => 'users#mypage', as: 'mypage'
    resources :users, only: [:show, :index]
    resources :plans do
      resources :comments, only: [:create, :destroy]
    end
    resources :spots do
      resources :spot_images, only: [:destroy]

    end
    get "search" => "searches#search"
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email] 
  #admin側でemail使ってログインするために必要
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  validates :text, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :spots, inverse_of: :plan, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :spots, allow_destroy: true, reject_if: :all_blank
  validates_associated :spots

  validates :title, presence: true, length: { maximum: 100 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_end_check

  def start_end_check
    errors.add(:end_date, "は旅行開始日より前の日付では登録できません。") unless
    self.start_date <= self.end_date 
  end

  def self.looks(search, word) #self.looks クラス全体にlooksメソッド使うためにself.使ってる。
    if search == "perfect_match" #完全一致の場合
      Plan.where("title LIKE?", "#{word}")
    elsif search == "forward_match" #前方一致
      Plan.where("title LIKE?","#{word}%")
    elsif search == "backward_match" #後方一致
      Plan.where("title LIKE?","%#{word}")
    elsif search == "partial_match" #部分一致
      Plan.where("title LIKE?","%#{word}%")
    else
      Plan.all #上の検索条件に当てはまらなかったら、全ユーザ取得する
    end
  end
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :spot

  enum transportation: {
    walk: 0, train: 1, bus: 2, car: 3, ship: 4, bicycle: 5, airplane: 6
  }

  validates :departure, presence: true
  validates :arrival, presence: true
  validates :visit_order,  presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :travel_time,  presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :plan 
  has_many :routes, inverse_of: :spot, dependent: :destroy
  accepts_nested_attributes_for :routes, allow_destroy: true, reject_if: :all_blank
  has_many_attached :images

  validates :name, presence: true, length: { maximum: 100 }
  validates :staying_start, presence: true
  validates :staying_end, presence: true
  validates :visit_order, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode

  validate :start_end_check

  def start_end_check
    errors.add(:staying_end, "は滞在開始時間より前の時間では登録できません。") unless
    self.staying_start <= self.staying_end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true 
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plans, inverse_of: :user,dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :profile_image
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.looks(search, word) #self.looks クラス全体にlooksメソッド使うためにself.使ってる。
    if search == "perfect_match" #完全一致の場合
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match" #前方一致
      User.where("name LIKE?","#{word}%")
    elsif search == "backward_match" #後方一致
      User.where("name LIKE?","%#{word}")
    elsif search == "partial_match" #部分一致
      User.where("name LIKE?","%#{word}%")
    else
      User.all #上の検索条件に当てはまらなかったら、全ユーザ取得する
    end
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin' #admin.html.erbを適用するため
  before_action :authenticate_admin!
  
  def show
    @user = User.find(params[:id])
    @plans = @user.plans
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_dashboards_path, notie: 'ユーザーを削除しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #ログイン認証が成功していないと、トップ/アバウトページ以外の画面(ログイン/サインアップ除く)表示されないように
  #エンドユーザー側のauthenticate_user!フィルターが適用されないように。かわりに管理者用コントローラで認証（authenticate_admin!)する
  before_action :authenticate_user!, except: [:top, :about], unless: :admin_controller? 
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile_image])
  end

  def after_sign_in_path_for(resource)
    mypage_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_update_path_for(resource)
    mypage_path
  end
  
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/spot_images_helper.rb
module SpotImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Travelers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/dc91daef60.js" crossorigin="anonymous"></script>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <%= image_tag('logo.png') %>
      <% if admin_signed_in? %>
        <div class="text-right">
          <%= link_to destroy_admin_session_path, method: :delete, class:'nav-link text-dark' do %>
            <i class="fa-solid fa-right-from-bracket"></i>管理者ログアウト
          <% end %>
        </div>
      <% else %>
        <div class="text-right">
          <%= link_to new_admin_session_path, class:'nav-link text-dark' do %>
            <i class="fa-solid fa-right-to-bracket"></i>管理者ログイン
          <% end %>
        </div>
      <% end %>
    </div>
  </nav>
  </header>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/dc91daef60.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= current_user ? user_path(current_user) : root_path %>">
            <%= image_tag('logo.png') %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to mypage_path, class:'nav-link text-dark' do %>
                    <i class="fa-solid fa-face-smile"></i> My page
                  <% end %>
                </li>
                <li>
                  <%= link_to plans_path, class:'nav-link text-dark' do  %>
                    <i class="fa-solid fa-person-walking-luggage"></i> プラン一覧 
                  <% end %>
                </li>
                <li>
                  <%= link_to new_plan_path, class:'nav-link text-dark' do %>
                    <i class="fa-solid fa-pencil"></i> 新規プラン投稿
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-dark' do %>
                    <i class="fa-solid fa-right-from-bracket"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to about_path, class:'nav-link text-dark' do %>
                    <i class="fa-solid fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to users_guest_sign_in_path, method: :post, class:'nav-link text-dark' do %>
                    <i class="fa-solid fa-face-grin-squint"></i> ゲスト Log in（閲覧用）
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class:'nav-link text-dark' do %>
                    <i class="fa-solid fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class:'nav-link text-dark' do %>
                    <i class="fa-solid fa-right-to-bracket"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class= m-3>
        <% flash.each do |key,message| %>
          <div class="flash <%= key %>"><%= message %></div>
        <% end %> 
      </div>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>